TRUNCATE TABLE CLIENT;
TRUNCATE TABLE ROLE;
TRUNCATE TABLE LIENVERSLABANDEANNONCE;
TRUNCATE TABLE FILMPAYSDEPRODUCTION;
TRUNCATE TABLE FILMGENRE;
TRUNCATE TABLE FILMSCENARISTE;
TRUNCATE TABLE FILM;
TRUNCATE TABLE PERSONNE;
TRUNCATE TABLE SCENARISTE;
TRUNCATE TABLE GENRE;
TRUNCATE TABLE PAYSDEPRODUCTION;


