TRUNCATE TABLE CLIENT;
TRUNCATE TABLE ROLE;
TRUNCATE TABLE LIENVERSLABANDEANNONCE;
TRUNCATE TABLE FILMPAYSDEPRODUCTION;
TRUNCATE TABLE FILMGENRE;
TRUNCATE TABLE FILMSCENARISTE;
TRUNCATE TABLE COPIEFILM;
TRUNCATE TABLE FILM;
TRUNCATE TABLE PERSONNE;
TRUNCATE TABLE SCENARISTE;
TRUNCATE TABLE GENRE;
TRUNCATE TABLE PAYSDEPRODUCTION;


DROP TABLE ABONNEMENT CASCADE CONSTRAINTS PURGE;
DROP TABLE CLIENT CASCADE CONSTRAINTS PURGE;
DROP TABLE COPIEFILM CASCADE CONSTRAINTS PURGE;
DROP TABLE EMPLOYEE CASCADE CONSTRAINTS PURGE;
DROP TABLE FILM CASCADE CONSTRAINTS PURGE;
DROP TABLE FILMGENRE CASCADE CONSTRAINTS PURGE;
DROP TABLE FILMPAYSDEPRODUCTION CASCADE CONSTRAINTS PURGE;
DROP TABLE FILMSCENARISTE CASCADE CONSTRAINTS PURGE;
DROP TABLE GENRE CASCADE CONSTRAINTS PURGE;
DROP TABLE LIENVERSLABANDEANNONCE CASCADE CONSTRAINTS PURGE;
DROP TABLE PAYSDEPRODUCTION CASCADE CONSTRAINTS PURGE;
DROP TABLE PERSONNE CASCADE CONSTRAINTS PURGE;
DROP TABLE RESERVATION CASCADE CONSTRAINTS PURGE;
DROP TABLE ROLE CASCADE CONSTRAINTS PURGE;
DROP TABLE SCENARISTE CASCADE CONSTRAINTS PURGE;
