@startuml
object "Client" as Client {
  *id_client : NUMBER(38) (PK)
  courriel : VARCHAR(255) (U)
  telephone : VARCHAR(255)
  mot_de_passe : VARCHAR(255)
  adresse : VARCHAR(255)
  ville : VARCHAR(255)
  province : VARCHAR(255)
  code_postal : VARCHAR(255)
  carte : {VARCHAR(15) CHECK value IN ('VISA','MasterCard','Amex')}
  numero : VARCHAR(255)
  cvv : VARCHAR(255)
  dateExpiration : DATE
}

object "Employee" as Employee {
  *id_employee : NUMBER(38) (PK)
  courriel : VARCHAR(255) (U)
  telephone : VARCHAR(255)
  mot_de_passe : VARCHAR(255)
  adresse : VARCHAR(255)
  ville : VARCHAR(255)
  province : VARCHAR(255)
  code_postal : VARCHAR(255)
}

object "Abonnement" as Abonnement {
  *code : char (PK)
  forfait : VARCHAR(255)
  cout : FLOAT
  location_max_copies : NUMBER(38)
  duree_max_jours : NUMBER(38) (NN)
}

object "Film" as Film {
  *id_film : NUMBER(38) (PK)
  titre : VARCHAR(255)
  anneeDeSortie : NUMBER(38)
  langue_originale : VARCHAR(255)
  duree_en_minutes : NUMBER(38)
  resume_scenario : VARCHAR(255)
  affiche : VARCHAR(255)
  realisateur_id : NUMBER(38) (FK,NN)
}

object "FilmScenariste" as FilmScenariste {
  nom : VARCHAR(255)
  film_id : NUMBER(38) (FK,NN)
  scenariste_id : NUMBER(38) (FK,NN)
}

object "Scenariste" as Scenariste {
  nom : VARCHAR(255)
}

object "FilmGenre" as FilmGenre {
  film_id : NUMBER(38) (FK,NN)
  genre_id : NUMBER(38) (FK,NN)
}

object "Genre" as Genre {
  *id_genre : NUMBER(38) (PK)
  nom : VARCHAR(255)
}

object "Acteur" as Acteur {
  nom : VARCHAR(255)
  prenom : VARCHAR(255)
  date_de_naissance : DATE
}

object "FilmPaysDeProduction" as FilmPaysDeProduction {
  id_film : NUMBER(38) (FK,NN)
  paysDeProduction_id : NUMBER(38) (FK,NN)
}

object "PaysDeProduction" as PaysDeProduction {
  *id_pays : NUMBER(38) (PK)
  nom : VARCHAR(255)
}

object "Role" as Role {
  *id_role : NUMBER(38) (PK)
  personnage : VARCHAR(255)
  acteur_id : NUMBER(38) (FK,NN)
  film_id : NUMBER(38) (FK,NN)
}

object "Réalisateur" as Réalisateur {
  id_realisateur : NUMBER(38) (PK)
  nom : VARCHAR(255)
  prenom : VARCHAR(255)
  date_de_naissance : DATE
}

object "CopieFilm" as CopieFilm {
  *numero_de_code : VARCHAR(255) (PK)
  est_retourner : BIT(1) 
  film_id : NUMBER(38) (FK,NN)
}

object "Location" as Location {
  *id_location : NUMBER(38) (PK)
  date_de_location : DATE
  date_de_retour_prevue : DATE
  client_id : NUMBER(38) (FK,NN)
  copieFilm_numero_de_code : VARCHAR(255) (FK,NN)
}

object "LienVersLaBandeAnnonce" as LienVersLaBandeAnnonce {
  *id_lien : NUMBER(38) (PK)
  lien : VARCHAR(255)
  film_id : NUMBER(38) (FK,NN)
}

Client ||--o{ Location
Film ||--o{ Role
Film ||--o{ Réalisateur
Film ||--o{ CopieFilm
CopieFilm ||--o{ Location
Acteur ||--o{ Role
PaysDeProduction ||--o{ Film
Film ||--o{ LienVersLaBandeAnnonce
Film ||--o{ FilmScenariste
Scenariste ||--o{ FilmScenariste
Genre ||--o{ FilmGenre
Film ||--o{ FilmPaysDeProduction
PaysDeProduction ||--o{ FilmPaysDeProduction
Abonnement ||--o{ Client
@enduml
