@startuml
entity "Client" as Client {
  *id_client : int <<PK>>
  courriel : string {unique}
  telephone : string
  mot_de_passe : string {>5 char alpha-numérique}
  adresse_id : int <<FK>>
}

entity "Adresse" as Adresse {
  *id_adresse : int <<PK>>
  adresse : string
  ville : string
  province : string
  code_postal : string
}

entity "CarteDeCredit" as CarteDeCredit {
  *id_carte : int <<PK>
  carte : string {VISA, MasterCard, Amex}
  numero : string
  cvv : string
  dateExpiration : Date
  client_id : int <<FK>>
}

entity "Abonnement" as Abonnement {
  *code : char <<PK>>
  forfait : string
  cout : float
  location_max_copies : int
  duree_max_jours : int {nullable}
}

entity "Film" as Film {
  *id_film : int <<PK>>
  titre : string
  anneeDeSortie : int
  langue_originale : string
  duree_en_minutes : int
  resume_scenario : string
  affiche : string
  genre_id : int <<FK>>
}

entity "Genre" as Genre {
  *id_genre : int <<PK>>
  nom : string
}

entity "Personne" as Personne {
  *id_personne : int <<PK>>
  nom : string
  prenom : string
  date_de_naissance : Date
}

entity "Acteur" as Acteur {
  personne_id : int <<FK>>
}

entity "Role" as Role {
  *id_role : int <<PK>>
  personnage : string
  acteur_id : int <<FK>>
  film_id : int <<FK>>
}

entity "Réalisateur" as Réalisateur {
  personne_id : int <<FK>>
  film_id : int <<FK>>
}

entity "CopieFilm" as CopieFilm {
  *numero_de_code : string <<PK>>
  est_retourner : bool
  film_id : int <<FK>>
}

entity "Location" as Location {
  *id_location : int <<PK>>
  date_de_location : Date
  date_de_retour_prevue : Date
  client_id : int <<FK>>
  copieFilm_numero_de_code : string <<FK>>
}

Adresse ||--o{ Client
Client ||--o{ CarteDeCredit
Client ||--o{ Location
Film ||--o{ Role
Film ||--o{ Réalisateur
Film ||--o{ CopieFilm
Personne ||--o{ Acteur
Personne ||--o{ Réalisateur
Genre ||--o{ Film
CopieFilm ||--o{ Location
Acteur ||--o{ Role
@enduml
